### ISSUE TITLE
refactor directory structure

### ISSUE THREAD

**Issue by KeisukeKatagiri** [BeerShigachi/sprout#2]
we need robust directory structure for feature changes.
todo
- [x] find good robust elm project to refer the architecture.
- [ ] refactor the directory architecture if needed.

breakdown:
https://dev.to/rtfeldman/tour-of-an-open-source-elm-spa

repo:
https://github.com/rtfeldman/elm-spa-example

**Comment by BeerShigachi** [comment]
Ideally the structure would be like this.
```
--sprout
----Page
------Top
--------TopPage.elm
--------TopPageComponent.elm
--------TopPageStyle.elm (if needed)
------About
------Common
--------baseComponent.elm
--------baseType.elm
--------baseStyle.elm
```
