### ISSUE TITLE
refactor toppage design

### ISSUE THREAD

**Issue by KeisukeKatagiri** [BeerShigachi/sprout#3]
**Refactoring the home page design.**
- [x] Creating an Elm that summarizes header candidates. (headerの候補をまとめたElmの作成。)
- [x] Creating an Elm that summarizes the main candidates.（メインの候補をまとめたElmの作成。）
- [x] Creation of Elm that summarizes button candidates.（ボタンの候補をまとめたElmの作成。）
- [x] Creating Elm that summarizes footer candidates.　（footerの候補をまとめたElmの作成。）
- [ ] Refactoring Top.elm based on the final design. (最終デザインを基にTop.elmのリファクタリング。)

src/Page/Wireframe/UserPageAcount/TopPage/TestPage/ will eventually be deleted.

**Comment by KeisukeKatagiri** [comment]
Under "refactor/refactor-toppage-design" branch
Create a dark mode screen in src/Page/Wireframe/UserPageAcount/TopPage/TestParts/TestTopPage.

**Comment by KeisukeKatagiri** [comment]
Under "refactor/refactor-toppage-design-lightDesign" branch
Create a light mode screen in src/Page/Wireframe/UserPageAcount/TopPage/TestParts/TestTopPage.

**Comment by BeerShigachi** [comment]
最終デザインはできてから実装すればよいので、それ以外ほとんども終わってますし、このissueはcloseします。
